---
HOSTS:
  ubuntu1604-64-1:
    pe_dir:
    pe_ver:
    pe_upgrade_dir:
    pe_upgrade_ver:
    platform: ubuntu-1604-x86_64 
    hypervisor: ec2
    amisize: c4.large
    snapshot: base
    user: ubuntu
    vmname: ubuntu-1604-x86_64
    roles:
      - master
      - agent
      - dashboard
      - databse
      - classifier
      - default
    host_tags:
      lifetime: 2h
  ubuntu1604-64-2:
    pe_dir:
    pe_ver:
    pe_upgrade_dir:
    pe_upgrade_ver:
    platform: ubuntu-1604-x86_64
    hypervisor: ec2
    amisize: c4.large
    snapshot: base
    user: ubuntu
    vmname: ubuntu-1604-x86_64
    roles:
      - agent    
    host_tags:
      lifetime: 2h
CONFIG:
  nfs_server: none
  consoleport: 443
